[package]

name = "rethinkdb"
version = "0.1.0"
authors = ["Tom Jakubowski <tom@crystae.net>"]

[lib]

name = "rethinkdb"
path = "src/rethinkdb/lib.rs"

[[example]]

name = "employees"
path = "examples/employees.rs"
